# Generated by Django 3.2.7 on 2021-10-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('image_person', models.ImageField(upload_to='uploads/')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'SingleBlog',
                'verbose_name_plural': 'SingleBlogs',
            },
        ),
    ]
