# Generated by Django 3.2.7 on 2021-10-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_singleblog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SingleBlog',
        ),
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
