# Generated by Django 3.2.7 on 2021-10-08 05:03

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211007_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('All Categories', 'All Categories'), ('LifeStyle', 'LifeStyle'), ('Food', 'Food'), ('Healthy', 'Healthy'), ('Sports', 'Sports'), ('Entertainer', 'Entertainer')], max_length=255),
        ),
    ]
