# Generated by Django 3.2.7 on 2021-10-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211008_0503'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('Video_link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='uploads/')),
            ],
            options={
                'verbose_name': 'HomeSection',
                'verbose_name_plural': 'HomeSections',
            },
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['id'], 'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('LifeStyle', 'LifeStyle'), ('Food', 'Food'), ('Healthy', 'Healthy'), ('Sports', 'Sports'), ('Entertainer', 'Entertainer')], max_length=255),
        ),
    ]
