# Generated by Django 3.2.7 on 2021-10-20 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20211020_0518'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Banner Section',
                'verbose_name_plural': 'Banner Sections',
            },
        ),
        migrations.RenameField(
            model_name='homesection',
            old_name='Video_link',
            new_name='video_link',
        ),
        migrations.CreateModel(
            name='SubBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('banner_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bannersection')),
            ],
            options={
                'verbose_name': 'Sub Banner',
                'verbose_name_plural': 'Sub Banners',
            },
        ),
    ]
